### ISSUE TITLE
Define storage endpoint using key vault

### ISSUE THREAD

**Issue by n8shadow** [Azure/AzureStor#10]
I am writing an application in a databricks notebook using R-language. The code must be capable to look into storage containers located in a data lake gen2 in order to list all their contents. 

So far I am doing the following for development

`endpoint <- AzureStor::adls_endpoint(endpoint = "https://<myStorageName>.dfs.core.windows.net", key = "<myStorageKey>") 
storage_containers <- AzureStor::list_storage_containers(endPoint)`

which works perfectly for me. This way I see all the containers in the data lake and can access them.

However, in order to become productive I must ban <myStorageKey> from the code which I hope is possible in principle using key vault since reading in a file works for me like this using

`%py
spark.conf.set("fs.azure.account.key.<myStorageName>.dfs.core.windows.net",
  dbutils.secrets.get(scope = "myScopeName", key = "mySecret") )`

`SparkR::read.df(path = "abfss://<myContainerName>@<myStorageName>.dfs.core.windows.net/<myFolderName>/<myFileName>.csv", source = "csv") -> mySparkDataFrame`

I started by trying to define the key vault applying the AzureKeyVault package 

`vault <- AzureKeyVault::key_vault(url ="https://<myKeyVaultName>.vault.azure.net")`

but this query runs forever such that I must cancle it manually. I guess this is an authentification issue?!

So, what is the correct way of defining a storage endpoint using the secret stored in a key vault, or of authentifying, respectively?

Thanks in advance for the support!

**Comment by Hong-Revo** [comment]
Are you trying to retrieve a storage account key that's stored in a Key Vault?

It looks like you're also using HDInsight or Databricks, in a Jupyter notebook. If so, you can try using the "device_code" authentication method:

```r
vault <- AzureKeyVault::key_vault("https://your-vault.vault.azure.net", auth_type="device_code")
```

**Comment by n8shadow** [comment]
Thanks for your comment! It seems that I missed to set up a service principle that allows to authentificate correctly via key vault, which might also be the reason that the query keeps on running without returning anything. I must now go deeper into this topic.

**Comment by Hong-Revo** [comment]
You should be able to use AzureKeyVault without creating a service principal; it uses the same SP as AzureRMR. The main thing is that in a Databricks environment, you can't use the default "authorization_code" method, which is intended for the scenario where you're running R on your local machine. The "device_code" method will still work though.
