### ISSUE TITLE
Allowing Header as arugment for access to remote resources requiring authentication

### ISSUE THREAD

**Issue by lshep** [Azure/AzureStor#106]
The Bioconductor group is finding your package very useful.  We have identified a fairly common use case for our users that they would like to transfer data from a github repo into our blob storage.  The `multicopy_url_to_storage` is very useful in this case; however it was giving me an error about rate limiting. Thinking a little more if one is authenticated to their github account, the rate limit is extended and could be useful.  Similarly, if there are other remote resources that require authentication, it currently isn't possible to use the `multicopy_url_to_storage` .  It seems like if the function passed a header argument where one could construct the necessary authentication credentials then it could be possible? https://stackoverflow.com/questions/70075161/downloading-file-from-a-private-repo-into-r/70076984#70076984

**Comment by hongooi73** [comment]
Hi, do you mean you're using AzureStor to copy from a Github repo into blob storage?

If so, can you give an example of the required header(s)? Note that because the request is routed via the storage service API, not all headers might be provided to the source.

**Comment by hongooi73** [comment]
I've pushed an implementation of this in the copyurl-auth branch. To use, supply the `auth_header` arg to `[multi]copy_url_to_storage`. For Github, this should be `token xxxxxx` with your PAT.

```r
copy_url_to_storage(cont, "https://raw.githubusercontent.com/acct/repo/branch/filename", "destfile",
    auth_header="token xxxxxx")
```

Let me know if you run into problems.

**Comment by lshep** [comment]
Thank you.  We will test this and thank you for the fast response!

**Comment by mtmorgan** [comment]
This fails with, e.g.,
```
> multicopy_url_to_storage(container, src=src, dest=dest)
Error in checkForRemoteErrors(val) : 
  27 nodes produced errors; first error: unused argument (auth_header = base::quote(NULL))
> traceback()
8: stop(count, " nodes produced errors; first error: ", firstmsg, 
       domain = NA)
7: checkForRemoteErrors(val)
6: staticClusterApply(cl, fun, vlen, argfun)
5: parallel::clusterMap(cl = .AzureR$pool, ...)
4: pool_map(function(s, d, lease, async) AzureStor::copy_url_to_blob(container, 
       s, d, lease = lease, async = async), src, dest, MoreArgs = list(lease = lease, 
       async = async, auth_header = auth_header))
3: multicopy_url_to_blob(container, src, dest, ...)
2: multicopy_url_to_storage.blob_container(container, src = src, 
       dest = dest)
1: multicopy_url_to_storage(container, src = src, dest = dest)

```

because
```
diff --git a/R/blob_copyurl.R b/R/blob_copyurl.R
index a0165d9..912300c 100644
--- a/R/blob_copyurl.R
+++ b/R/blob_copyurl.R
@@ -77,7 +77,7 @@ multicopy_url_to_blob <- function(container, src, dest, lease=NULL, async=FALSE,
     init_pool(max_concurrent_transfers)
 
     pool_export("container", envir=environment())
-    pool_map(function(s, d, lease, async) AzureStor::copy_url_to_blob(container, s, d, lease=lease, async=async),
+    pool_map(function(s, d, lease, async, auth_header) AzureStor::copy_url_to_blob(container, s, d, lease=lease, async=async, auth_header),
              src, dest, MoreArgs=list(lease=lease, async=async, auth_header=auth_header))
     invisible(NULL)
 }
```

**Comment by hongooi73** [comment]
I've just pushed the fix to the copyurl-auth branch.

**Comment by mtmorgan** [comment]
Actually, `auth_header` needs to be added as an argument to the anonymous function
```
pool_map(function(s, d, lease, async, auth_header)
                                       ^^^^^^^^^^
```

**Comment by hongooi73** [comment]
Argh, really fixed now

**Comment by lshep** [comment]
Thank you!
