### ISSUE TITLE
Exploration of sub-folders/directories in a file system of a data lake

### ISSUE THREAD

**Issue by n8shadow** [Azure/AzureStor#11]
I am writing R-code in an Azure Databricks notebook that is supposed to explore a data lake since latter is supplied by many (partially unknown) sources. Using AzureStor I started doing the following code

`AzureStor::adls_endpoint(endpoint = "https://<myDLName>.dfs.core.windows.net",
                         key = myAccessKey) -> endP`
`AzureStor::list_storage_containers(endP) -> storage_containers`
`paste0("https://", myDLName,".dfs.core.windows.net/", names(storage_containers)[1] ) -> path`
`AzureStor::adls_filesystem(path, mykAccessLKey) -> myFileSys`
`AzureStor::list_adls_files(myFileSys, "/") -> myFiles`

which outputs a R data.frame named "myFiles" having columns like "name" and "isDirectory" which I really appreciate. Now, if for some row of the "myFiles" data.frame "isDirectory" is TRUE, I would my code like to go with the exploration, i.e. look into the directory, list the objects in there and so on. Just extending the endpoint url by "/myFolder" and using this  

In the end of the day, the task is to read all files (mostly .csv) into the session wich are present in an unknown folder structure. How can that be achieved using AzureStor?

**Comment by Hong-Revo** [comment]
`list_adls_files(*, recursive=TRUE)` should give you a recursive listing of all subdirectories.

**Comment by n8shadow** [comment]
Works fine for me! How could I only miss that in the documentation. 
Thanks a lot!
