### ISSUE TITLE
Include delete_snapshots parameter in delete_blob() and delete_blob_dir()

### ISSUE THREAD

**Issue by icctr** [Azure/AzureStor#113]
If snapshots exists, `delete_blob()` and `delete_blob_dir()` fail with the error message: "This operation is not permitted because the blob has snapshots." Deleting snapshots could be implemented using a `delete_snapshots` parameter taking the arguments NULL, "include", or "only". If not NULL, the argument should be passed on to the header [`x-ms-delete-snapshots`](https://docs.microsoft.com/en-us/rest/api/storageservices/delete-blob#request-headers).

**Comment by hongooi73** [comment]
Full snapshot support is in the latest update, can you give it a go and let me know if you run into problems?
