### ISSUE TITLE
Using token auth breaks

### ISSUE THREAD

**Issue by Biebrya** [Azure/AzureStor#119]
Per my previous closed issue:
https://github.com/Azure/AzureStor/issues/118#issue-1166826438

This is the error that comes back from the service when I use token auth *instead* of access keys. 

Error in process_storage_response(response, match.arg(http_status_handler),  : 
  Unauthorized (HTTP 401). Failed to complete Storage Services operation. Message:
InvalidAuthenticationInfo
Server failed to authenticate the request. Please refer to the information in the www-authenticate header.
RequestId:b61c87bf-101e-0023-4f82-35914e000000
Time:2022-03-11T20:01:42.6298813Z
Audience validation failed. Audience did not match.

When I looked at the header all I saw was this:
"Bearer authorization_uri=https://login.microsoftonline.com/<client_id>/oauth2/authorize resource_id=[https://storage.azure.com"]()

Talking with microsoft rapid response team they told me that it was due to the shared access key not being turned on for storage. If I auth using a token, why would the shared access key need to be turned on?

**Comment by hongooi73** [comment]
Don't make a duplicate issue.
