### ISSUE TITLE
Error in curl::curl_fetch_memory(url, handle = handle) :    Timeout was reached:

### ISSUE THREAD

**Issue by rhaumoraes** [Azure/AzureStor#122]
cont <- blob_container("https://mystorage.blob.core.windows.net/", sas="my_sas")
arq <- list_blobs(cont, dir = dataRef, info="name")

Connection error, retrying (1 of 10)
Connection error, retrying (2 of 10)
Connection error, retrying (3 of 10)
Connection error, retrying (4 of 10)
Connection error, retrying (5 of 10)
Connection error, retrying (6 of 10)
Connection error, retrying (7 of 10)
Connection error, retrying (8 of 10)
Connection error, retrying (9 of 10)
Connection error, retrying (10 of 10)
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: [mystorage.blob.core.windows.net] Connection timed out after 10006 milliseconds

This error started showing up a month ago

**Comment by hongooi73** [comment]
I don't think this has anything to do with AzureStor. There's probably an issue with the network between you and Azure; check that your workplace hasn't installed any new firewalls, for example.
