### ISSUE TITLE
TLS Support

### ISSUE THREAD

**Issue by GreyMerchant** [Azure/AzureStor#131]
Hello, 

Currently we are looking at changing our TLS version related to our storage accounts on Azure. One of the things which we wanted to confirm was if this package will remain compatible for later versions of TLS? Can you advise if specific versions of AzureStor are only compatible with certain versions of TLS?

**Comment by hongooi73** [comment]
AzureStor uses the curl package, which should support every TLS version that isn't actively deprecated. So you're good.
