### ISSUE TITLE
Queue storage package available

### ISSUE THREAD

**Issue by Fuco1** [Azure/AzureStor#14]
Hi.  I'm doing some batch processing and I would like after each batch the R process to write into a queue so that other parts of the pipeline can pick up the process.

Is there any time-frame for azure storage queue support?

**Comment by Hong-Revo** [comment]
It's not on the roadmap currently, but it could be. 😊 Can you give me some more information about your use case? Is another kind of storage (file/blob/ADLS2) a possible alternative?

**Comment by Fuco1** [comment]
I'm writing data to blob storage but then placing a tiny message with a link to the queue.  The queue storage ensures that the message is only visible to one consumer (until they confirm it is processed) and reinstalls the message in case of node failure.  So the queue behaviour is pretty convenient.

We can also "work around" this by setting up some events on blob storage where an event is pushed to the queue on blob creation.  This is probably even a better solution, but due to political reasons I can't use the events on my subscription and it can take a lot of time until it is available.

**Comment by bradleyboehmke** [comment]
Two things:

1. The documentation for `storage_endpoint()` implies that you can create a storage endpoint for a queue.  I would suggest removing this or making it more explicit that support for queues are currently not available.
2. We are transitioning to Azure and plan to write from R and Python to a queue, which will then feed to Cosmos DB.  We want one consistent architecture for both languages but currently we cannot write to a queue with R.  Having this added functionality would be ideal unless there is a more efficient alternative.

**Comment by Hong-Revo** [comment]
I'll see if I can pump something out by the end of the year. It'll probably be in a new package (that imports AzureStor, so you can talk to all kinds of storage easily).

**Comment by fermar9** [comment]
I need to consume azure queue messages. It would be great to do it using R script.

**Comment by Hong-Revo** [comment]
There is now an [AzureQstor](https://github.com/Azure/AzureQstor) package for working with queues. It's still at an early stage of development; the docs are fairly basic, and the tests aren't finished yet. The functionality should all be there though.

From the readme:

> AzureQstor uses a combination of S3 and R6 classes. The queue endpoint is an S3 object for compatibility with AzureStor, while R6 classes are used to represent queues and messages.

```r
library(AzureQstor)

endp <- storage_endpoint("https://mystorage.queue.core.windows.net", key="access_key")

# creating, retrieving and deleting queues
create_storage_queue(endp, "myqueue")
qu <- storage_queue(endp, "myqueue")

qu2 <- create_storage_queue(endp, "myqueue2")
delete_storage_queue(qu2)
```

The queue object exposes methods for getting (reading), peeking, popping (reading and deleting) and putting (writing) messages.

```r
qu$put_message("Hello queue")
msg <- qu$get_message()

msg$text
## [1] "Hello queue"
```

The message object exposes methods for deleting and updating the message.

```r
msg$update(visibility_timeout=30, text="Updated message")
msg$delete()
```

**Comment by Fuco1** [comment]
@Hong-Revo Thanks for the work!  Unfortunately my project is now suspended due to COVID related troubles.  When we get back to it I'll check it out more in depth!

**Comment by Hong-Revo** [comment]
This is now [on CRAN](https://cloud.r-project.org/package=AzureQstor)
