### ISSUE TITLE
Allow using custom endpoint URL format to support Azurite

### ISSUE THREAD

**Issue by grthr** [Azure/AzureStor#16]
Currently, the call to `is_endpoint_url` enforces the default Azure URL format, also documented in the source code:

> endpoint URL must be of the form {scheme}://{acctname}.{type}.{etc}

However, the Azure storage emulator tool _Azurite_ does not follow this schema.

Instead of `<http|https>://<account-name>.<service-name>.core.windows.net/<resource-path>`, Azurite uses `http://<local-machine-address>:<port>/<account-name>/<resource-path>`.

Is it possible to disable the format check of the endpoint URL in case of directly calling `blob_endpoint` function?

**Comment by Hong-Revo** [comment]
Seems fairly straightforward. As a workaround until I get this done, you can create a blob endpoint with a dummy URL and then just replace the `$url` component of the object with the Azurite endpoint.

**Comment by Hong-Revo** [comment]
I've just pushed an update that changes the `stop` to a `warning` when you pass an unrecognised URL to `blob_endpoint`. This should enable Azurite use; you can use `suppressWarnings` if you don't want to see the warning.
