### ISSUE TITLE
function to move or copy blobs from one container to a different container

### ISSUE THREAD

**Issue by abfleishman** [Azure/AzureStor#17]
I am wanting to move or copy blobs between two containers that may or may not be in the same storage account.  It would be nice to have a method to do so.  Also, it would be nice to be able to supply a vector of names to have a multi copy version or this.

**Comment by Hong-Revo** [comment]
The `copy_url_to_storage` function will let you copy files from an Internet URL to blob storage. This works for source storage accounts too; include a SAS in the URL for the blob if it's not public.

```r
copy_url_to_storage(bl_cont,
    "https://srcaccount.blob.core.windows.net/container/blob?sv=....",
    "destblob")
```

I'm actually working on vectorised multiple file transfers right now. Should be able to merge it into master in the next week or so.

**Comment by abfleishman** [comment]
Ok I will try that out.  I will just have to figure out how to build the path to the blobs that I want to copy.

**Comment by Hong-Revo** [comment]
#18
