### ISSUE TITLE
avoid prompt when library(AzureStor)

### ISSUE THREAD

**Issue by ldfreight** [Azure/AzureStor#2]
Hello,

is there a way to avoid the prompt when we load the package?
This might be an issue when run as a script?

**Comment by Hong-Revo** [comment]
The prompt actually comes from AzureAuth, and only appears if you're running R in interactive mode. In a batch script, the directory won't be created if it doesn't already exist.

**Comment by ernestomonroy** [comment]
Despite what @hongooi73 has said, the prompt is: a) extremely annoying when running in interactive mode b) unncesessary as it can be configured as a warning + environment variable and c) not best practice when comparing with most high quality R packages

You should seriously consider re-opening the ticket and doing something about it

**Comment by vidarsumo** [comment]
To clarify, I have an R script scheduled within a Docker container (rocker/tidyverse), which I plan to deploy via Azure Container Instances. For testing purposes I've been running the Docker container locally and this prompt appear everytime. My question is, when the script is scheduled to run within the ACI context, will this prompt still be presented?
