### ISSUE TITLE
Write/read directly to memory

### ISSUE THREAD

**Issue by edwinschut** [Azure/AzureStor#21]
Is there a possibility to read/write (for any file type) directly into R memory from a adls gen2 storage? For example:  on a gen2 file storage I have a  text.csv file which I like to read with read_csv  to a  dataframe.  

The current solution I came up with is first to download the file to a temporary local directory and then use read_csv.

**Comment by Hong-Revo** [comment]
The universal solution is to write to a temp file, and read that. Even if there's a wrapper, that's still what is happening underneath.

If you're using Spark file formats, the possibility that the data is larger than your available memory can't be ignored. So you must write to a file.

**Comment by Hong-Revo** [comment]
I'm going to guess that when you say "write/read directly to memory", what you really mean is "provide wrappers to make the 2-step process (write to temp file + do file transfer) more convenient". Is this right?

**Comment by edwinschut** [comment]
With the arrow package there is the possibility to read parquet files without spark. We are using azure Data factory to transform different sources to 1 file type (parquet).  I am looking for a convenient + fast way to read /write this files in R form a gen2 storage (blob/file share). (and indeed there is file size to take into account). 

A more general approach is to use the current "wrappers" like read_csv, read_xlsx with the path to gen2. It would be great if we can use the endpoint definition as path (like a file path to a local disk).

**Comment by Hong-Revo** [comment]
… yeah, it doesn't work like that.

I suggest writing some simple wrappers like

```r
read_csv_from_adls <- function(path, ...)
{
    fname <- tempfile()
    download_from_url(path, fname, ...)
    read_csv(fname)
}
```

Repeat this pattern for all your file types.

**Comment by TCC-TCP-DM** [comment]
I think the practicality from an Azure client's perspective makes the idea of wrappers native to the AzureStor package worth development.  It just makes the package more adaptable for the user who may not want to write their own functions for this.  It also allows AzureR to remain competetive with [Python which can do this already, I think.](https://docs.microsoft.com/en-us/azure/machine-learning/team-data-science-process/explore-data-blob)
