### ISSUE TITLE
Creation-Time is not part of the properties, but is expected in list_blobs

### ISSUE THREAD

**Issue by wligtenberg** [Azure/AzureStor#25]
Using an earlier version of AzureStor, we were able to successfully upload files into the blob storage and retrieve them.
After the update to version 3.0.0 the list_storage_files function fails with the following error message:

```Error in as.POSIXct.default(df$`Creation-Time`, format = "%a, %d %b %Y %H:%M:%S",  : 
  do not know how to convert 'df$`Creation-Time`' to class “POSIXct”```

After soem investigation, we have found this issue to be causes by line 332 in: https://github.com/Azure/AzureStor/blob/36317e84a81e3f6496324d3efc6faf56c65e233e/R/blob_client_funcs.R

In our case the Creation-Time is not part of the properties returned on this line:
```lst <- res$Blobs```

Our initial thought was to delete the files and upload them again using AzureStor 3.0.0, unfortunately, this didn't solve the issue at hand.

**Comment by Hong-Revo** [comment]
I can't reproduce this error. Can you provide more details on your storage account? Kind ("StorageV2" or whatever), blob tier, location, API version, etc.

**Comment by wligtenberg** [comment]
Azure blob storage endpoint
URL: https://<some_random_bit>standardsa.blob.core.windows.net/
Access key: <none supplied>
Azure Active Directory token: <none supplied>
Account shared access signature: <hidden>
Storage API version: 2018-11-09

Azure blob container '<name>'
URL: https://>some_random_bit>standardsa.blob.core.windows.net/blob
Access key: <none supplied>
Azure Active Directory access token: <none supplied>
Account shared access signature: <hidden>
Storage API version: 2018-11-09

We upload the files from an Ubuntu 16.04 system. (which might be related, since Creation-Time might not be in the metadata of a file.) The files come from a cifs mount with the following options:
 type cifs (rw,relatime,vers=3.02,sec=ntlmssp,cache=strict,uid=0,noforceuid,forcegid,file_mode=0770,dir_mode=0770,nounix,mapposix,rsize=1048576,wsize=1048576,echo_interval=60,actimeo=1)

**Comment by Hong-Revo** [comment]
The metadata of the source filesystem shouldn't matter; the creation time should be the time when it was uploaded... what happens if you upload a file from your local drive?

**Comment by Hong-Revo** [comment]
(And upload to a new blob container, so that any blank metadata from your current container won't mess with the results.)

**Comment by wligtenberg** [comment]
I cannot easily get a new blob container (I don't have the authorization to do so), but I removed all the existing files and uploaded some files that were not on the blob storage before and I get the same error.
These files were uploaded from a local ext4 disk. (even though that shouldn't matter)

Is there any other information that I can request that should be of help?

**Comment by Hong-Revo** [comment]
The storage account properties would be good to know. You may have to ask your admin for this info, depending on what permissions you have.

- In the portal, go to the storage account resource and take screenshots of the Overview and Properties panes.

- Alternatively, you can use AzureRMR:

```
library(AzureRMR)
library(AzureStor)
az <- get_azure_login("your_tenant")
res <- az$get_subscription("your_sub_id")$
          get_resource_group("rgname")$
          get_storage_account("acctname")

res$location
res$kind
res$properties
```

**Comment by Hong-Revo** [comment]
I've just made a commit that should work around this problem with `list_blobs`. Let me know if it works.

Also, you can try running `do_container_op(cont, options=list(comp="list", restype="container"))` and post the results. This will show the raw output from the endpoint, as a list translated from XML.

**Comment by Hong-Revo** [comment]
Similar issue reported by email:

> I am a R developer from INDIA. I am using AzurStor library for some data conversion purpose for which I am pulling the files from Azure Data Blob.
But recently I have notice the code is blocking to pull Last_Modified_Date from Data Blob.

**Comment by Hong-Revo** [comment]
dd97dbb

**Comment by wligtenberg** [comment]
@Hong-Revo Thanks for the fix! I hope to see it on CRAN soon.

**Comment by Hong-Revo** [comment]
No worries. I'd still like to see the result of `do_container_op(cont, options=list(comp="list", restype="container"))` though. I still can't repro the bug and I'd like to know if the field is genuinely missing or I'm just getting the capitalisation wrong or something else.
