### ISSUE TITLE
Limit output of list_storage_files

### ISSUE THREAD

**Issue by Triamus** [Azure/AzureStor#31]
Would be helpful if one could define a query in the call to list_storage_files(), e.g. files modified after some date or simply maxresult = some value. Not sure if that is even possible in the rest api but it seems so telling form [MS Docs: REST API Reference - List Blobs](https://docs.microsoft.com/en-us/rest/api/storageservices/list-blobs). A similar question was asked on SO in the context of a C# client, see [StackOverflow: Getting the latest file modified from Azure Blob](https://stackoverflow.com/questions/36266792/getting-the-latest-file-modified-from-azure-blob).

**Comment by Hong-Revo** [comment]
Yes, it's possible to do this in the REST call. However, you can also simply filter the result of `list_storage_files` in R, eg using dplyr's `filter` or `arrange` -- this would probably be the simplest solution, unless you really have tons of files and pulling all the rows across the network is slowing you down.

**Comment by Triamus** [comment]
Yes I know. I just have a data lake full of small json and the retrieve of the meta data already takes quite some time. So I thought a query pushdown would be useful. Was just an idea. Not that important. Thanks.

**Comment by Hong-Revo** [comment]
There is actually no way right now to filter a file list on the server side. Best alternative would be to use `prefix` to limit the result to only files that match on the first characters of the (path/file) name.
