### ISSUE TITLE
download_blob fails inside lapply.... sometimes

### ISSUE THREAD

**Issue by abfleishman** [Azure/AzureStor#35]
I am using `download_blob` inside `lapply` to download a list of blobs. When I have a large list of blobs it sometimes (not always) fails after downloading some of the blobs with the error below.  Any thoughts on a better way to code this?  Is there some way to avoid this?  The problem is the program hangs and does not through an error until the `Esc` key is hit by the user.  Thank you in advance!

```
lapply(unique(totag_sub$download_path),
                    function(x){
                      download_blob( container = cont_image,
                                     src = x,
                                     dest =paste0(tagging_location,"/",x) ,overwrite = T)
                    })
```

> |============================================================================================================================| 100%
>   |============================================================================================================================| 100%
>   |============================================================================================================================| 100%
>   |============================================================================================================================| 100%
>   |============================================================================================================================| 100%
>   |===========                                                                                                                 |   9%
> Connection error, retrying (1 of 10)
>   |      

>  Error in download_blob_internal(container, src, dest, blocksize = blocksize,  : 
>   Forbidden (HTTP 403). Failed to complete Storage Services operation. Message:
> AuthenticationFailed
> Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
> RequestId:a1a2e308-901e-0062-5902-c4087b000000
> Time:2020-01-05T19:57:57.9797635Z
> Request date header too old: 'Sun, 05 Jan 2020 11:42:07 GMT'.

**Comment by Hong-Revo** [comment]
You should be able to use `multidownload_blob` to do this automatically with a list of filenames. Each download will be handled independently of the others, so one failure won't cause all remaining files to be skipped.

I'll look into why the auth failure is happening.

**Comment by Hong-Revo** [comment]
#36

**Comment by Hong-Revo** [comment]
I've just pushed a fix for this. Can you try it out, and let me know if the problem persists?

**Comment by abfleishman** [comment]
I will download the latest but in the past, there have been changes that broke some of my code when I have updated the package (i.e. capitalization of column names in the table produced by `list_blobs`) so it might take a bit before I can test since I am using the code in production...  I am probably going to use the `multidownload_blob` function in the future anyway, but that you for addressing this!

**Comment by abfleishman** [comment]
@Hong-Revo I have not received the error I initially reported since you made the fix.  Thank you!
