### ISSUE TITLE
AzureStor fails to install in Azure Compute Instance

### ISSUE THREAD

**Issue by edocastro** [Azure/AzureStor#40]
I created an Azure Workspace and a Compute Instance, after the compute instance is created I launched R Studio from the column named Application URI. The R Studio load but when I run the command install.packages("AzureStor") it not installed it displays the following error:

Using PKG_CFLAGS=
Using PKG_LIBS=-lxml2
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because libxml-2.0 was not found. Try installing:
 * deb: libxml2-dev (Debian, Ubuntu, etc)
 * rpm: libxml2-devel (Fedora, CentOS, RHEL)
 * csw: libxml2_dev (Solaris)
If libxml-2.0 is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a libxml-2.0.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------------
ERROR: configuration failed for package ‘xml2’
* removing ‘/home/azureuser/R/x86_64-pc-linux-gnu-library/3.6/xml2’
Warning in install.packages :
  installation of package ‘xml2’ had non-zero exit status
ERROR: dependency ‘xml2’ is not available for package ‘roxygen2’
* removing ‘/home/azureuser/R/x86_64-pc-linux-gnu-library/3.6/roxygen2’
Warning in install.packages :
  installation of package ‘roxygen2’ had non-zero exit status
ERROR: dependency ‘xml2’ is not available for package ‘rversions’
* removing ‘/home/azureuser/R/x86_64-pc-linux-gnu-library/3.6/rversions’
Warning in install.packages :
  installation of package ‘rversions’ had non-zero exit status
ERROR: dependency ‘xml2’ is not available for package ‘AzureStor’
* removing ‘/home/azureuser/R/x86_64-pc-linux-gnu-library/3.6/AzureStor’
Warning in install.packages :
  installation of package ‘AzureStor’ had non-zero exit status

**Comment by Hong-Revo** [comment]
Hi, this isn't related to AzureStor. As the message says, you need to install a system library first. Assuming you're using an Ubuntu instance, you should be able to do this by running `sudo apt-get libxml2-dev` in a terminal window. Once that's done, rerun `install.packages` in R.

Consider also raising the lack of system libraries on the MS feedback forum: https://feedback.azure.com/forums/257792-machine-learning
