### ISSUE TITLE
upload_blob failing

### ISSUE THREAD

**Issue by abfleishman** [Azure/AzureStor#43]
I have been using `upload_blob` in production for months and just 3 days ago it began to fail.  I am uploading a CSV from an active r session to a blob storage container.  This is not a repex but here is the code.
It begins to upload (rapidly at first) and then pauses for several minutes before printing "connection failure.  Eventually, I get an error message. Thoughts? the csv is only 4510 rows of 11 columns so not a big file and this used to run almost instantly.

```
# create a text connection to the tagged data to upload
con_tagged<-textConnection(object = format_csv(tagged_upload))
 # upload it to the blob container
upload_blob(cont_labels, src=con_tagged,
       dest=paste0("tagged_",round(as.numeric(Sys.time())*1000),".csv"),
       use_azcopy = F)
```

> 
>   |========================================================                                              |  55%Connection error, retrying (1 of 10)
>   |=====================                                                                                 |  21%Connection error, retrying (2 of 10)
>   |==================                                                                                    |  17%Connection error, retrying (3 of 10)
>   |==========================================                                                            |  41%Connection error, retrying (4 of 10)
>   |==============                                                                                        |  14%Error in process_storage_response(response, match.arg(http_status_handler),  : 
>   Forbidden (HTTP 403). Failed to complete Storage Services operation. Message:
> AuthenticationFailed
> Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
> RequestId:4945a495-901e-001a-479e-ed322b000000
> Time:2020-02-27T18:46:45.1205751Z
> Request date header too old: 'Thu, 27 Feb 2020 18:31:44 GMT'.

**Comment by abfleishman** [comment]
I have also received this error 

> Error in process_storage_response(response, match.arg(http_status_handler),  : 
>   Internal Server Error (HTTP 500). Failed to complete Storage Services operation. Message:
> OperationTimedOut
> Operation could not be completed within the specified time.
> RequestId:31e2144f-101e-0014-2fa3-ed1b9b000000
> Time:2020-02-27T19:28:11.7238069Z.

**Comment by Hong-Revo** [comment]
The timeout looks like a network/server error. The "Request date header too old" message should have been solved by the latest update, what version are you using?

**Comment by abfleishman** [comment]
I have version 3.1.0.9000 just updated from github.  I was also receiving the error when using the latest cran version.  Just to clarify, is the network issue is on the Azure end of things or on my local connection end of things?

**Comment by Hong-Revo** [comment]
I suspect there's a glitch in Azure somewhere. Your request got to the server, but for whatever reason it couldn't be fulfilled.

**Comment by abfleishman** [comment]
hmm..  ok.  Any advice on how to move forward?  Or dig into the issue further?  Other people I should contact?

**Comment by Hong-Revo** [comment]
I would contact tech support. The RequestId's that get printed out should help them track down what's going on.

**Comment by abfleishman** [comment]
strange. looks like I have to pay to make a support request for technical issues.

**Comment by Hong-Revo** [comment]
Yes, support is a paid option. I can't help with that unfortunately.

**Comment by Hong-Revo** [comment]
So, it turns out the stale date problem wasn't really fixed after all. I've pushed a commit that should fix it for sure. (But the issue with timeouts is still likely due to an Azure glitch.)

**Comment by abfleishman** [comment]
ok!  Thank you.  I am still working with tech support to try and resolve the timeouts.
