### ISSUE TITLE
download_from_url function not working

### ISSUE THREAD

**Issue by macambo** [Azure/AzureStor#44]
I am trying to use the download_from_url function from the AzureStor package. I keep getting the below error

Error in download_blob_internal(container, src, dest, blocksize = blocksize, : Forbidden (HTTP 403). Failed to complete Storage Services operation. Message: .

I know that it should work and the permissions are set up correctly for the storage account because I am able to download the blob using Python.

**Comment by Hong-Revo** [comment]
What is the output of your `sessionInfo()`?

Also, have you tried the other download functions (`storage_download`, `download_blob`)?

**Comment by macambo** [comment]
Yes, I've tried both download_blob and storage download. Here is the error message I am getting. 
![image](https://user-images.githubusercontent.com/22012611/76016570-0efcde80-5eeb-11ea-83a7-903a140e928c.png)

My code is `endp <- storage_endpoint("<URL>",
                         key = "<StorageKey>")
cont <- storage_container(endp, "<BlobContainerName>")
list_blobs(cont)
#list blobs works

storage_download(cont, src = "Simulation-Algorithm-Input.json", dest = "Simulation-Input.json", overwrite = TRUE)
download_blob(cont, src = "Simulation-Algorithm-Input.json", dest = "Simulation-Input.json", overwrite = TRUE)`

My Session Info is 
![image](https://user-images.githubusercontent.com/22012611/76016779-7450cf80-5eeb-11ea-8d4c-79743b549aa0.png)

**Comment by macambo** [comment]
It is working for me now. I used this piece of code. 

endp <- storage_endpoint("https://acctname.blob.core.windows.net", key="access_key")
cont <- storage_container(endp, "mycontainer")
storage_download(cont, "myblob.csv", "local_filename.csv")

from https://stackoverflow.com/questions/54851723/access-azure-blob-storage-from-r-notebook

Thanks
