### ISSUE TITLE
list_blob_containers, missing nextmarker iteration

### ISSUE THREAD

**Issue by StatKalli** [Azure/AzureStor#46]
Hi all,

I notice `list_blob_containers` does not iterate on the `NextMarker` like the `list_blobs` function.

I need `list_blob_containers` to return the entire list of containers from my account and not just the first elements.

Example :
``` R
> connection<- AzureStor::blob_endpoint(endpoint = endpoint, key = key)
> names(AzureStor::list_blob_containers(connection))
[1] "db-tab-1"             "db-tab-2"
```
But in reality, I have more containers, I should have something like
``` R
> connection<- AzureStor::blob_endpoint(endpoint = endpoint, key = key)
> names(AzureStor::list_blob_containers(connection))
[1] "db-tab-1"             "db-tab-2"             "db-tab-3"             "db-tab-4"
```
So to fix that, just include the iteration on `NextMarker` 😄 or did I miss something on my code? 🤔 

Thank you!

**Comment by Hong-Revo** [comment]
Hm, how many containers do you have?? The default should return up to 5000.

**Comment by StatKalli** [comment]
19..but I don't know why only the 2 first names returned. I notice if I iterate with the `NextMarker` like `list_blobs` function I have the others, sorry maybe I repeat myself 😟

**Comment by Hong-Revo** [comment]
Can you try with the ADLS endpoint? You can work with blob and ADLS containers using either API. It should be as simple as replacing "blob" with "dfs" in the storage endpoint URL.

```
endp <- storage_endpoint("https://youracct.dfs.core.windows.net", *)
list_storage_containers(endp)
```

**Comment by StatKalli** [comment]
![image](https://user-images.githubusercontent.com/37298740/77931642-f094c380-729b-11ea-956d-d70b0803f3d3.png)
I think I don't have it

**Comment by Hong-Revo** [comment]
I don't know what software that is. Give it a go anyway, it might work.

**Comment by StatKalli** [comment]
The software is Azure Explorer.

I tried your proposition :
``` R
> endp <- AzureStor::storage_endpoint("https://myaccount.dfs.core.windows.net", key = key)
> list_storage_containers(endp)
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Could not resolve host: myaccount.dfs.core.windows.net
```

**Comment by StatKalli** [comment]
I managed to recode `list_blob_containers()`  function for my need :
``` R
list_blob_containers <- function(endpoint, ...) {
  res <- call_storage_endpoint(endpoint, "/", options = list(comp = "list"))
  lst <- lapply(res$Containers, function(cont) blob_container(endpoint, cont$Name[[1]]))

  while (length(res$NextMarker) > 0) {
    res <- call_storage_endpoint(endpoint, "/", options = list(comp = "list", marker = res$NextMarker[[1]]))
    lst <- c(lst, lapply(res$Containers, function(cont) blob_container(endpoint, cont$Name[[1]])))
  }
  named_list(lst)
}
```

**Comment by Hong-Revo** [comment]
Thanks!

**Comment by StatKalli** [comment]
Hi again! 

Thanks for the update, I immediately test it by updating AzureStor package but...I still not have my entire list of containers 😅

On the same az account of 19 containers, this time I get 12 (compared to the first time with only 2). It's like it does not enter in the last loop.

I don't know why or if you have change something else in the package? I notice that the `while` condition change but it could not be that I suppose 🤔

**Comment by Hong-Revo** [comment]
The `is_empty()` function is just

```
function (x)
{
    length(x) == 0
}
```

so it should be doing exactly the same thing as your code. I'm not sure what's going on. I'll make a new branch for testing this.

**Comment by Hong-Revo** [comment]
See if the 'list-markers' branch solves this. I've reverted to your condition.

**Comment by StatKalli** [comment]
Yeah I knew, it is AzureRMR function 😄 for `is_empty()`

I'm gonna try 'list-containers' branch :)

**Comment by StatKalli** [comment]
It works... 😅

**Comment by Hong-Revo** [comment]
If you have the time, you can try digging around to see what's going on. Just add a few `print` statements inside `list_blobs` to see what the API is returning. I'll add this fix for file shares as well.
