### ISSUE TITLE
list_storage_files isdir=TRUE for files after uploading with azcopy

### ISSUE THREAD

**Issue by Naedri** [Azure/AzureStor#52]
Hi,
First of all, thanks for the works you do with the AzureRFamily !
As it is shown in the following snap : 

![image](https://user-images.githubusercontent.com/56276737/84013184-e288b080-a978-11ea-93ae-b118740ea47d.png)

(The above files were uploaded with the followng command : `storage_multiupload(cont, paste0(img_path,"*"),  dest="azcopy", use_azcopy=TRUE)`)

When I listing the different elements of a blob container with the following command : 
`list_storage_files (cont, info ="all")`, the *isdir* colunm indicates `isdir=TRUE` even if it is an image.  

I can manage what I want to do with the *Content-Type* column, but I am still wondering if the *isdir* column indicates whether the element is a file or directory. If it is not the case I think the name *isdir* could be reformulated, what do you think ?

Sincerely yours,

**Comment by Hong-Revo** [comment]
Looks like azcopy handles the lease-related fields slightly differently to what I expected. In the meantime, if you set `use_azcopy=FALSE` (the default), it should work as expected.

**Comment by Naedri** [comment]
Thanks for your quick answer Hongooi73 !
