### ISSUE TITLE
storage_download fails on very small file

### ISSUE THREAD

**Issue by scottporter** [Azure/AzureStor#65]
The storage_download function may work on larger files, but I caused weird timeouts on very small files (the iris dataset, as shown in the documentation examples).  I put together a reproducible example to demonstrate.  I tracked down the place in the code where the process hangs to the place where the size of the file is computed for the progress bar, but haven't yet figured out exactly what about the logic is causing it to hang.

Perhaps the source of the issue will be obviously apparent to someone more familiar with the package.  If not, perhaps the logic could instead be borrowed from the list_blobs function... it may not be as exact, but I had no trouble getting file sizes for the small files using this function.

Code to produce error:
```
username="myusername"
storage_account<-"mystorageaccountname"
container_name<-"mycontainername"
access_key<-"myaccesskey"

storage_endpoint_url<-"https://${storage_account}.blob.core.windows.net"
storage_endpoint_url_resolved<-glue::glue(storage_endpoint_url,.open="${")

bl_endp_key <- AzureStor::storage_endpoint(storage_endpoint_url_resolved, 
                                    key=access_key
                                    )
AzureStor::list_storage_containers(bl_endp_key)

cont<-AzureStor::create_storage_container(bl_endp_key,name=container_name)
json <- jsonlite::toJSON(iris, pretty=TRUE, auto_unbox=TRUE)
con <- textConnection(json)
AzureStor::storage_upload(cont, src=con, dest="iris.json")

AzureStor::list_blobs(cont)
### will fail on next line (times out ten times in a row)
## it gets stuck here: https://github.com/Azure/AzureStor/blob/a71fcf88a9bd7b97c8ab221aaf3ced813d0265db/R/blob_transfer_internal.R#L83
## if I change the http_verb from "HEAD" to "GET" it finishes, so perhaps there's something wrong in the logic
## with regard to very small file sizes?  
rawvec <- AzureStor::storage_download(cont, src="iris.json", dest=NULL)
rawToChar(rawvec)


### alternate workaround to show the file is fine and downloadable

tenant_id<-"mytenantid"
subscription_id<-"mysubscriptionid"
resource_group_name<-"myresourcegroupname"

az <- AzureRMR::create_azure_login(tenant=tenant_id,auth_type="device_code")
sub <- az$get_subscription(subscription_id)
rg <- sub$get_resource_group(resource_group_name)
stor <- rg$get_resource(type="Microsoft.Storage/storageAccounts", name=storage_account)
rdevstor1 <- rg$get_storage_account(storage_account)
my_sas<-rdevstor1$get_account_sas(permissions="r",services="bf", start=Sys.Date(), expiry=Sys.Date() + 31)

my_blob_endpoint<-rdevstor1$get_blob_endpoint()
l_endp_sas <- AzureStor::storage_endpoint(storage_endpoint_url_resolved, sas=my_sas)
adm_cont <- AzureStor::storage_container(l_endp_sas, container_name)

test_url<-paste0(storage_endpoint_url_resolved,"/",container_name,"/iris.json?",my_sas)
test_download<-jsonlite::fromJSON(test_url)
testthat::expect_equal(test_download,jsonlite::fromJSON(jsonlite::toJSON(iris)))

```

**Comment by hongooi73** [comment]
I can't reproduce this problem. What are the details for your storage account?

**Comment by scottporter** [comment]
I set up a brand new storage account in preparation for a training.  

Here are the details:
* Location
   * East US 2
* Performance/Access tier
   * Standard/Hot
* Replication
   * Locally-redundant storage (LRS)
* Account kind
   * StorageV2 (general purpose v2)

Our version of R is a bit dated (3.4.1).  I can also try in another environment on a newer version of R and see if I can replicate there as well.  And I'll if I can figure out how to export you a SAS key to try with.

**Comment by scottporter** [comment]
I'll dig into it a bit more on Linux R 3.4.1 and if I can diagnose the issue I'll send a proposed change.

**Comment by hongooi73** [comment]
You may have an outdated httr on your R 3.4.1 box. See if installing the latest versions from CRAN helps.

**Comment by scottporter** [comment]
Yes, installing httr 1.4.2 fixes the issue.  We were previously running 1.2.1.  So, somewhere in between, something happened.  I tried installing all the versions of httr in between.  The first version of httr to not cause an issue was 1.4.0, so that should probably be required as a dependency.

**Comment by hongooi73** [comment]
b47dcd1e778027b04956b92f575f111dae748a38
