### ISSUE TITLE
Accessing storage emulator from Azure SDK

### ISSUE THREAD

**Issue by thuwas** [Azure/AzureStor#66]
I am using the AzureSDK storage emulator for development. 
https://docs.microsoft.com/en-us/azure/storage/common/storage-use-emulator

Can anyone help me with creating the storage endpoint to access the Azure storage emulator?

Tried the following:
library(AzureStor)
endp <- storage_endpoint("http://127.0.0.1:10000/devstoreaccount1")

Error: Unknown endpoint type

endp<-storage_endpoint("UseDevelopmentStorage=true")
Error: Unknown endpoint type

**Comment by hongooi73** [comment]
To access the emulated endpoint, you'll need to use one of the type-specific endpoint functions:

```r
adls_endpoint("http://127.0.0.1/devstoreaccount1")
blob_endpoint("http://127.0.0.1/devstoreaccount1")
file_endpoint("http://127.0.0.1/devstoreaccount1")
```

You'll get a warning, but it can be ignored. Let me know if you run into problems, it should work but I haven't tried using the package with an emulator.

**Comment by thuwas** [comment]
Thanks for the response.

I managed to find the queue endpoint and tried the following:

library(AzureStor)
library(AzureQstor)

> endpoint <- queue_endpoint("http://127.0.0.1:10001/devstoreaccount1/")
Warning message:
Not a recognised queue endpoint 
> create_storage_queue(endpoint, "myqueue1")
Error in process_storage_response(response, match.arg(http_status_handler),  : 
  Not Found (HTTP 404). Failed to complete Storage Services operation. Message:
ResourceNotFound
The specified resource does not exist.
RequestId:25c8e900-f489-4a07-be98-e6d42468f86f
Time:2020-08-17T00:17:17.4250133Z.

What could be wrong?

**Comment by hongooi73** [comment]
Did you remember to include the shared key?

**Comment by thuwas** [comment]
yes:
> endpoint <- queue_endpoint("http://127.0.0.1:10001/devstoreaccount1",key="Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==")
Warning message:
Not a recognised queue endpoint 
> create_storage_queue(endpoint, "myqueue1")
Error in process_storage_response(response, match.arg(http_status_handler),  : 
  Not Found (HTTP 404). Failed to complete Storage Services operation. Message:
ResourceNotFound
The specified resource does not exist.
RequestId:64f11f15-9c0f-465e-a971-88cb404c7a61
Time:2020-08-17T04:30:09.0564570Z.
>

**Comment by hongooi73** [comment]
Can you check to see if it works with blob storage? I need to know whether it's something in AzureStor or AzureQStor causing the problem.

**Comment by thuwas** [comment]
It's not working with blob storage:

> library(AzureStor)
> endp<-blob_endpoint("http://127.0.0.1:10000/devstoreaccount1",key="Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==")
Warning message:
Not a recognised blob endpoint 
> list_blob_containers(endp)
Error in process_storage_response(response, match.arg(http_status_handler),  : 
  Bad Request (HTTP 400). Failed to complete Storage Services operation. Message:
InvalidInput
One of the request inputs is not valid.
RequestId:5039ffcf-fed2-44e3-95ab-771f4038361d
Time:2020-08-18T00:11:34.9193421Z.
> container<-blob_container(endp,'mycontainer')
> list_blobs(container)
Error in process_storage_response(response, match.arg(http_status_handler),  : 
  Not Found (HTTP 404). Failed to complete Storage Services operation. Message:
ResourceNotFound
The specified resource does not exist.
RequestId:1018f38b-1cb0-4a7a-9f77-dc406dbddf47
Time:2020-08-18T00:12:20.3603885Z.

**Comment by hongooi73** [comment]
What version of the storage emulator are you using?

**Comment by thuwas** [comment]
5.10

**Comment by thuwas** [comment]
https://docs.microsoft.com/en-us/azure/storage/common/storage-use-emulator

**Comment by hongooi73** [comment]
Can you try using [Azurite](https://github.com/azure/azurite) instead? Will help to determine if this is a flaw in the package, or something in the Azure SDK emulator?

**Comment by thuwas** [comment]
With Azurite:
![image](https://user-images.githubusercontent.com/41892235/90575758-768bb980-e1ff-11ea-95fb-3cb70ff08ad4.png)

> endp<-blob_endpoint("http://127.0.0.1:10000/devstoreaccount1/",key="Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==")
Warning message:
Not a recognised blob endpoint 
> list_blob_containers(endp)
Error in process_storage_response(response, match.arg(http_status_handler),  : 
  Bad Request (HTTP 400). Failed to complete Storage Services operation. Message:
InvalidQueryParameterValue
Value for one of the query parameters specified in the request URI is invalid.
RequestId:14ce8513-092e-4973-aeda-2f1f2e0af8a9
Time:2020-08-18T08:03:43.002Z.

**Comment by hongooi73** [comment]
Ok, supporting the storage emulator is more complicated than I assumed at first. This may take some time.

**Comment by hongooi73** [comment]
You can try the branch [emulator-support](https://github.com/Azure/AzureStor/tree/emulator-support), it should work with both Azurite and the Azure SDK emulator.

To authenticate with Azurite:

```r
# see the Azurite repo for how to setup your acct/key details
bl <- blob_endpoint("http://127.0.0.1:10000/myaccount", key="mykey"
qu <- AzureQstor::queue_endpoint("http://127.0.01:10001/myaccount", key="mykey")
```

To authenticate with the Azure SDK:

```r
bl <- blob_endpoint("http://127.0.0.1:10000/devstoreaccount1",
    key="Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw=="
```

**Comment by thuwas** [comment]
Yes. It works fine with the blob storage.
Thank you.

I tried the AzureQStor:

![image](https://user-images.githubusercontent.com/41892235/90995038-049be180-e5fe-11ea-9334-f0e9fcec8112.png)

Should we need any fix in the AzureQStor?

**Comment by thuwas** [comment]
Ah sorry, I picked the wrong endpoint. It works fine with the AzureQStor. 
![image](https://user-images.githubusercontent.com/41892235/90995257-baffc680-e5fe-11ea-97da-d8d02ab1b11b.png)


Thank you.
