### ISSUE TITLE
`list_blobs` doesn't honor `dir` when paging is used.

### ISSUE THREAD

**Issue by AshesITR** [Azure/AzureStor#69]
The requests for new pages in `list_blobs()` don't include the `prefix` parameter.
This means filtering on `dir` only applies to the first page of blobs listed. All other pages are unfiltered.

https://github.com/Azure/AzureStor/blob/b0dcdff5336e9b2fb0d35ed648a9903f8d02c9cd/R/blob_client_funcs.R#L342

**Comment by hongooi73** [comment]
Thanks for reporting this, it should now be fixed in master. Let me know if the bug is still there.
