### ISSUE TITLE
Unable to download blob from container

### ISSUE THREAD

**Issue by rafaelschlatter** [Azure/AzureStor#7]
Hi,

I am unable to download blobs from my storage account. I followed the documentation in the readme, this is my code:

I can successfully create an endpoint and get a container with
````r
bl_endp_key <- storage_endpoint("url", "key")
cont <- storage_container(bl_endp_key, "container_name")
````

I can further successfully list my containers and files in the blob like this:
````r
list_storage_containers(bl_endp_key)
list_storage_files(cont)
````

But when I try to download a blob, the call takes very long and fails due to a connectionerror. It then tries to reconnect for 10 times and fails every time. This is the code i use:

````r
rawvec <- download_blob(cont, src="blob_name", dest=NULL)
````

My container has container access level (anonymous read access for containers and blobs). I used the Azure storage account access key to create the endpoint. I can access the same blob in python using the same storage account access key.

Do you know what I am doing wrong?

**Comment by Hong-Revo** [comment]
If you have anonymous read access enabled, try leaving out the `key` argument to `storage_endpoint`. You can also try downloading with base R's `download.file` to confirm that the blob is accessible.

**Comment by Hong-Revo** [comment]
I was able to download a blob from a container with anonymous access enabled, both to a file and to a raw connection. Can you provide more details on your storage account?

**Comment by rafaelschlatter** [comment]
I was able to download the file with R base `download.file()`. I am also able to upload files to the container, but still no luck with downloading blobs. Tried leaving away the `key` argument as well.
Tried with `src="container_name/blob_name"` and `src="blob_name"` only, but neither was successfull.

About my storage account: Type: BlobStorage, blob public access level: Container (anonymous read access for containers and blobs), location North Europe, I have no SAS enabled and no access roles defined except me as the service adminstrator. I allowed access from all networks and use HTTPs.

**Comment by Hong-Revo** [comment]
What type of blob is it? AzureStor only supports block blobs, not page and append blobs.

**Comment by rafaelschlatter** [comment]
Its a block blob. Its something to do with my company's network. Works from home with this function: `storage_download(cont, "myblob", "myfile", overwrite=TRUE)`

Should have tried with a different network, apologies.
Thanks for the help. Im closing this.
