### ISSUE TITLE
ADLS Gen 2 Posix

### ISSUE THREAD

**Issue by howardginsburg** [Azure/AzureStor#76]
I'm trying to figure out how to connect up to my ADLS Gen 2 account and have posix permissions based on user credentials.  I've confirmed connectivity via either the Storage Key or the App Registration.  I can't figure out how to get a token that is specific to the user.  Is this possible?  Is there an example?  Thanks!

**Comment by hongooi73** [comment]
Your title refers to POSIX by which I assume you mean ADLS ACLs, but your text refers to getting a token, which I assume means you're trying to authenticate using AAD with `get_azure_token`. What exactly are you trying to do, and where is it going wrong?

**Comment by howardginsburg** [comment]
@hongooi73 , I'm not the best with R, so let me paint a picture of the problem and hopefully you can help guide me.

1. RStudio Server Pro running on an Azure VM with AAD authentication enabled.
2. ADLS Gen 2 with folder permissions assigned to users.
3. From within an RStudio session, users need to be able to read/write to folders based on their permissions.

We thought this library would be the way to go for that.

**Comment by hongooi73** [comment]
Yes, you use AzureStor to access storage with a minimum number of dependencies.

Here's what I think you want to do. I assume you already have the storage account setup, with the users granted Storage Blob Data Contributor permissions.

1. Get an AAD token. This will authenticate as the user (not as the app), using the device code flow. The device code is needed if you're using RStudio Server.
   ```r
   library(AzureAuth)
   library(AzureStor)
   tok <- get_azure_token("https://storage.azure.com/", tenant="tenantname", app="appid", auth_type="device_code")
   ```
2. Use the token when creating the endpoint object:
   ```r
   endp <- storage_endpoint("https://acctname.blob.core.windows.net", token=tok)

   # a storage container
   cont <- storage_container(endp)
   # do stuff with the container
   ```

I don't have much experience with POSIX ACLs, but I assume they just work off the user account. You may also want to post on StackOverflow or the RStudio community forums if you need more assistance.

**Comment by hongooi73** [comment]
Closing, since this doesn't appear to be related to AzureStor. If you're still having problems, email me or try asking on one of those sites.
