### ISSUE TITLE
acquire lease always returns 400 error

### ISSUE THREAD

**Issue by officialpatterson** [Azure/AzureStor#77]
Working on a project the now where we store cran packages on an azure storage account working as a static site. I was hoping to use this package, but the acquire lease function doesn't seem to work.
```
>   AzureStor::acquire_lease(container, blob = "NEWS.md")
Error in process_storage_response(response, match.arg(http_status_handler),  : 
  Bad Request (HTTP 400). Failed to complete Storage Services operation. Message:
InvalidUri
The requested URI does not represent any resource on the server.
RequestId:e6525ecb-001e-0052-7590-005651000000
Time:2021-02-11T16:12:54.7789968Z.
```
I'm sure the blob exists as I've ran the function to check it exists and it returns true:
```
> AzureStor::blob_exists(container, "NEWS.md")
[1] TRUE
```

Any help would be appreciated.

**Comment by hongooi73** [comment]
Thanks for reporting this; the lease functions should be fixed now.
