### ISSUE TITLE
upload_blob with lease produces error.

### ISSUE THREAD

**Issue by officialpatterson** [Azure/AzureStor#78]
Pulled the latest changes from master and I think there is still incomplete features. I was able to successfully acquire a lease for a blob, but when I went to upload a new one in its place while providing the lease ID I get the below error message. My first thought is that the lease parameter in upload_blob isn't been correctly transformed into the parameter needed by azcopy?
```
Error in process_storage_response(response, match.arg(http_status_handler),  : 
  Precondition Failed (HTTP 412). Failed to complete Storage Services operation. Message:
LeaseIdMissing
There is currently a lease on the blob and no lease ID was specified in the request.
RequestId:00304a4d-301e-0040-35aa-03f1e0000000
Time:2021-02-15T14:51:32.0396637Z. 
```

**Comment by hongooi73** [comment]
1. Please provide the actual code that you ran that produced the error
2. May I ask the reason you're using azcopy? Is there a feature that the regular AzureStor functions don't have that you need?

**Comment by officialpatterson** [comment]
The code I use is below. you can assume that self$mutex points to a lease string created by the acquire lease functions.
`AzureStor::upload_blob(self$container, src = file.path(tempDir, "PACKAGES.rds"), dest = "src/contrib/PACKAGES.rds",lease = self$mutex)`

I'm not using azcopy, sorry for the confusion. I guessed it might have been azcopy but it might not have anything to do with it.

**Comment by hongooi73** [comment]
This should be fixed in the `lease-fix` branch.

**Comment by officialpatterson** [comment]
The lease-fix branch has resolved this thank you.

**Comment by hongooi73** [comment]
Interesting; thanks to your comment I've discovered that azcopy doesn't actually support leases....
