### ISSUE TITLE
Missing sample for AAD Authorization against ADLS Gen2 

### ISSUE THREAD

**Issue by ralphke** [Azure/AzureStor#79]
Could not find a sample on how to use my credentials to authorize access to ADLS Gen2 container/folder. None of the provided samples is explicit enough to get something working. Within our team we have been struggling to get this basic capability to work.  
Any help is much appreciated to sign-in with AAD credentials and pass-thru these to the ADLS storage for read and write operations.

**Comment by hongooi73** [comment]
This isn't much to go on. What is the code you're running, and what error do you get?

**Comment by timoklimmer** [comment]
Thanks for your quick answer, @hongooi73. We could successfully authenticate with a service principal. Our problem is that we don't know how to authenticate without app id, service principal etc. The scenario is that data scientists want to access ADLS Gen2 from their notebook (or maybe a Compute Instance from Azure ML), not having to configure extra service principals etc. (as these concepts are all too complicated for them). The wish/expectation is rather that data scientists are shown a browser window where they login as usual. Is that scenario supported at all?

**Comment by hongooi73** [comment]
Yes, if you can create the app/service principal, you will get the usual AAD login experience. To authenticate with AzureAuth as shown above, you'll need to give the app a native ("mobile & desktop") redirect URI of `http://localhost:1410`, or if using the device code flow, enable the "allow public client flows" setting.

The assumption here is that the end user (data scientist) will either create the app, or get someone else to do it for them. AzureStor doesn't register an app ID of its own; it just provides the API to access storage. As a workaround, you can also use the Az CLI's app ID: `04b07795-8ddb-461a-bbee-02f9e1bf7b46`.

I can add some documentation to this effect.

**Comment by ralphke** [comment]
@hongooi73  Thanks for sharing your insights here. It is great work you are doing for the community with this repro. THANK YOU.
There are two critical elements in your answers, which I at least have not been aware of. 
1. redirect to localhost:1410 instead of localhost:8080 (default)
2. using the AZ CLI app ID 04b07795-8ddb-461a-bbee-02f9e1bf7b46
3. would it be possible to use the VSCode App ID also?
4. how to find out the related App ID of a given App?

**Comment by hongooi73** [comment]
Thanks! Port 8080 is what RStudio Server uses, but port 1410 seems to be the default for the OAuth authorization code flow. I don't know where it came from, but it's used by the Az CLI, the PnP [CLI for MS 365](https://github.com/pnp/cli-microsoft365), the Azure Data Explorer app, and several others.

I found the CLI app ID by looking in its token cache: c:\\users\\{username}\\.azure\\accessTokens.json on Windows. If you copy the tokens into a JWT viewer like https://jwt.ms, you'll see the contents including the app ID. You could give the VSCode app ID a go as well, although it may not have the correct permissions to access storage.

I'm not sure if there is a general way to detect the ID for a given app -- maybe use tools like Wireshark to snoop on the network traffic? I know nothing about stuff like that, sorry.

**Comment by hongooi73** [comment]
AAD vignette now on CRAN: https://cran.r-project.org/web/packages/AzureStor/vignettes/aad.html
