### ISSUE TITLE
list_adls_files() normalise output missed "lastModified"

### ISSUE THREAD

**Issue by klin333** [Azure/AzureStor#82]
In "R/adls_client_funcs.R" lines 320 (master branch), various columns are normalised to give defaults if they are missing. However, it missed the 'lastModified' column.

Please consider adding something like this:
`
if (is.null(dfchunk$lastModified)) 
      dfchunk$lastModified <- ""
`

I am brand new to Azure, and came across this when trying to fix errors stemming from calling list_storage_files() on directories others created outside of AzureStor, which were missing columns that needed the defaults of line 320 onwards but still needed a default for lastModified.

**Comment by hongooi73** [comment]
Thanks for the report. This should now be fixed.
