### ISSUE TITLE
Possible Speed Improvements for storage_read_csv

### ISSUE THREAD

**Issue by KoderKow** [Azure/AzureStor#85]
Hello,

Thanks for this great package! Before `storage_read_csv` was created I wrote a function for reading data from a container. There are options for using `readr::read_csv`, `vroom::vroom`, and `data.table::fread`. I did a `bench::mark()` test on my function compared to what is on CRAN and have the below as a result. Apologies, I cannot provide any reproducibility due to there being private work information in the code currently.

The data has a size of `35625456` in the storage container and has 47,519 rows with 96 columns.

![image](https://user-images.githubusercontent.com/23486577/115793360-9e847b80-a391-11eb-8acf-a36b0487b4fa.png)

I understand not wanting to bring in {data.table} or {vroom} as dependencies, but I would love your thoughts on possibly improving the reading speed for `storage_read_csv`. I only work with containers so I would need assistance with knowing if my approach would work in all situations. I can make a PR if this sounds good!

**Comment by hongooi73** [comment]
Are you using readr/vroom/dt to read directly from the storage URL?

**Comment by KoderKow** [comment]
Yep! I can make a PR tomorrow, I would love your thoughts!

**Comment by hongooi73** [comment]
Note that `storage_read_csv` should already be using `readr::read_csv` if it's available. Can you show the code you're running?

**Comment by KoderKow** [comment]
Yes, I can share the function I wrote for reading from containers to in-memory! I did make a PR for improving the reading speed from {readr}

```
#' @title Read a csv file into a tibble from the data lake
#'
#' @description Read in a csv from the data lake.
#'
#'
#' @param container A storage container object.
#' @param src A character. The source file to bring into R. Ex: "data/my_data.csv"
#' @param engine A character. The engine to read in the csv file. The `col_types` param will not be used when the engine is set to `fread`
#' - **fread**: `data.table::fread()`
#' - **read_csv**: `readr::read_csv()` (Default)
#' - **vroom**: `vroom::vroom()`
#' @param ... Additional parameters to pass to the **engine** functions.
#'
#' @family Azure Data Lake Functions
#'
#' @return A tibble
#' @export
#'
#' @examples
#' \dontrun{
#'   dl_read_csv(
#'     container = cont,
#'     src = "data/iris.csv"
#'   )
#' }
dl_read_csv <- function(
  container,
  src,
  engine = "read_csv",
  ...
) {
  con <- rawConnection(raw(0), "r+")

  AzureStor::storage_download(
    container = container,
    src = src,
    dest = con
  )

  if (engine == "fread") {
    d <- con %>%
      rawConnectionValue() %>%
      rawToChar() %>%
      data.table::fread(
        sep = ",",
        ...
      )

    close(con)
  } else if (engine == "vroom") {
    d <- vroom::vroom(
      file = con,
      delim = ",",
      altrep = FALSE,
      ...
    )
  } else if (engine == "read_csv") {
    d <- readr::read_csv(
      file = con,
      ...
    )

    close(con)
  } else {
    usethis::ui_stop(
      "Invalid engine. Please check the documentation for valid engines.
    - Run {usethis::ui_code('?dl_read_csv')} in your RStudio Console."
    )
  }

  return(d)
}
```

A few notes:
- {readr} and {vroom} can read from connections
- `close(con)` does not work on the connection after `vroom::vroom(...)` interacts with it
  - Adding `altrep = FALSE` seems to have silenced the connection warnings
- `data.table::fread()` cannot read from a connection directly, so I turned that into a string, similar to how it is currently being done with {readr} in this package

**Comment by hongooi73** [comment]
See comment at #86
