### ISSUE TITLE
Service SAS support (for individual blob access longer then 7 days)

### ISSUE THREAD

**Issue by docss-rvdm** [Azure/AzureStor#89]
The user_delegated_sas can not be longer then 7 days. And I need a sas to access a single blob(file) for longer then 7 days.
This is possible creating a 'service sas'. But it's not supported.

Could you add the service_sas as a third option?

**Comment by hongooi73** [comment]
I can do that, but have you tried using an account SAS? That should work for longer than 7 days.

**Comment by docss-rvdm** [comment]
Thank you for your swift response. The problem with the account sas is that the sas-token gives access to potentially every blob-file in the container. That is a security threat for my use case. I want to have a different sas for each blob-file in the container. And a service SAS can be created for an individual blobfile.

Please read this documentantion
https://docs.microsoft.com/en-us/azure/storage/blobs/sas-service-create?tabs=dotnet

Please feel free to ask any questions.

































.
