### ISSUE TITLE
Connection error with readr 2.0.0

### ISSUE THREAD

**Issue by nik-humphries** [Azure/AzureStor#95]
A close connection error is achieved when using readr 2.0.0. Code works fine on readr 1.4.0. Readr makes the connection invalid after reading from it.

Tested using 
```
AzureStor::storage_read_csv(container = my_container,
                                           file = fileName,
                                           ...)
```
which returns the error
```
Error in close.connection(con) : invalid connection

```

You can test connections not being closed properly by running the following
```
con <- rawConnection(raw(0), "r+")
writeBin("hiya", con)
readr::read_csv(con)
con

close(con)
```

```
Error in close.connection(con) : invalid connection
```

Looking at con gives `A connection, specifically, ‘rawConnection’, but invalid.`

Unsure if this is an issue for the readr package, or if something that can be handled within here.

**Comment by hongooi73** [comment]
Looks like `read_delim` behaviour changed between readr 1.4.0 and 2.0.0 so that it now automatically closes connections.

I'll fix AzureStor to handle this, but you might want to raise this issue at the [readr repo](https://github.com/tidyverse/readr) as well.

**Comment by hongooi73** [comment]
You may also be able to work around this problem by setting the readr edition to 1, see `?readr::with_edition`

**Comment by nik-humphries** [comment]
I raised an issue here, it seems as though this is intended behaviour for readr 2.0.0.

https://github.com/tidyverse/readr/issues/1261

**Comment by vidarsumo** [comment]
Had the same issue, setting the edition to 1 solved it.

**Comment by hongooi73** [comment]
This should now be fixed in the dev version. Let me know if the problem persists.

**Comment by nik-humphries** [comment]
Excellent - thanks.
