### ISSUE TITLE
azure_storage_progress_bar is set to TRUE in .onLoad

### ISSUE THREAD

**Issue by CharlesCara** [Azure/AzureStor#96]
Hi

This is a great project and very helpful for me.  However, it creates a lot of messages about uploading and downloading files which are not always necessary in production systems and which interfer with rknitr output.

Please can you remove:
options(azure_storage_progress_bar=TRUE)
from .onLoad so that settings in a users .RProfile file is respected.

As a user of this great package (and the other Azure packages), I would suggest that the defaults should be that it works silently without messages, with the option to switch on messages if needed for debugging purposes.

Thank you

**Comment by hongooi73** [comment]
This is now in the dev version, let me know if you run into problems

**Comment by CharlesCara** [comment]
Thank you
